sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t lasupernova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test